# -*- coding: utf-8 -*-
"""customer sales analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WSSXJDtzzKbijlXdgjP1spKg_3GjJS-g
"""



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from fpdf import FPDF

# Load the sales dataset
df = pd.read_csv("customer_sales_data.csv")

# Display first 5 rows
print(df.head())

# Convert date column to datetime format
df['Purchase Date'] = pd.to_datetime(df['Purchase Date'])

# Extract year and month for analysis
df['Year-Month'] = df['Purchase Date'].dt.to_period('M')

# Checking for missing values
print(df.isnull().sum())

# Display summary statistics
print(df.describe())

# Group by Year-Month and calculate total revenue
monthly_sales = df.groupby('Year-Month')['Total Purchase Amount'].sum()

# Plot sales trend
plt.figure(figsize=(15,5))
sns.lineplot(x=monthly_sales.index.astype(str), y=monthly_sales.values, marker="o", linewidth=2, color="blue")
plt.xticks(rotation=45)
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Revenue")
plt.grid()
plt.show()

# Group by product and sum up quantity sold
top_products = df.groupby('Product Category')['Quantity Purchased'].sum().sort_values(ascending=False)

# Plot best-selling products
plt.figure(figsize=(10,5))
sns.barplot(x=top_products.index, y=top_products.values, palette="viridis")
plt.title("Best-Selling Products")
plt.xlabel("Product")
plt.ylabel("Total Quantity Sold")
plt.show()

# Group by customer and calculate total spending
top_customers = df.groupby('Customer ID')['Total Purchase Amount'].sum().sort_values(ascending=False)

# Display top 5 customers
print(top_customers.head(5))

# Scatter plot to analyze correlation
plt.figure(figsize=(8,5))
sns.scatterplot(x=df['Price per Item'], y=df['Quantity Purchased'], alpha=0.7)
plt.title("Price vs Quantity Sold")
plt.xlabel("Price")
plt.ylabel("Quantity Sold")
plt.show()

# Prepare data for ML model
df['Month'] = df['Purchase Date'].dt.month
df['Year'] = df['Purchase Date'].dt.year
sales_data = df.groupby(['Year', 'Month'])['Total Purchase Amount'].sum().reset_index()

# Train-Test Split
X = sales_data[['Year', 'Month']]
y = sales_data['Total Purchase Amount']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train Model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict Future Sales
y_pred = model.predict(X_test)

# Evaluate Model
mae = mean_absolute_error(y_test, y_pred)
print(f"Mean Absolute Error: {mae}")

# Predict Next Month’s Sales
next_month = pd.DataFrame({'Year': [2025], 'Month': [3]})  # Predict for March 2025
predicted_sales = model.predict(next_month)
print(f"Predicted Sales for March 2025: {predicted_sales[0]:.2f}")

# Create PDF Report
pdf = FPDF()
pdf.set_auto_page_break(auto=True, margin=15)
pdf.add_page()
pdf.set_font("Arial", style='', size=12)

# Title
pdf.set_font("Arial", style='B', size=16)
pdf.cell(200, 10, "Customer Sales Analysis Report", ln=True, align='C')

# Add Key Insights
pdf.set_font("Arial", size=12)
pdf.cell(200, 10, f"Total Revenue: {df['Total Purchase Amount'].sum():,.2f}", ln=True)
pdf.cell(200, 10, f"Top Product: {df.groupby('Product Category')['Quantity Purchased'].sum().idxmax()}", ln=True)

# Save PDF
pdf.output("sales_report.pdf")
print("PDF Report Generated!")